version: '3'

services:
  flask_app:
    container_name: CoffeeAI-DLBackend
    restart: always
    build: ./CoffeeAI-DLBackend
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app
  